language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c 'CREATE DATABASE questioner_test;' -U postgres
  - psql -c 'CREATE DATABASE questioner;' -U postgres

script:
  - pytest --cov=app/

after_success:
  - coveralls